
version: '{branch}.{build}'

#cache:
#  - c:\build-cache
#  - c:\build-cache\sdk

environment:
  PHP_BUILD_CACHE_BASE_DIR: c:\build-cache
  PHP_BUILD_OBJ_DIR: c:\obj
  PHP_BUILD_CACHE_SDK_DIR: c:\build-cache\sdk
  PHP_BUILD_SDK_BRANCH: php-sdk-2.2.0
  SDK_REMOTE: https://github.com/Microsoft/php-sdk-binary-tools.git
  SDK_BRANCH: php-sdk-2.2.0

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_REL: 8.0
      ZTS_STATES: enable disable
      PHP_BUILD_CRT: vs16
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_REL: 8.1
      ZTS_STATES: enable disable
      PHP_BUILD_CRT: vs16

platform:
        - x86
        - x64

install:
  - appveyor\install.cmd

build_script:
  - appveyor\build.cmd

test_script:
  - appveyor\test.bat

artifacts:
  - path: artifacts
    name: php_win32service-%APPVEYOR_REPO_TAG_NAME%-%PLATFORM%-%PHP_REL%
    type: zip
deploy:

- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: GrQFyIPHIWQ12XchDACv4MfGCsj1ch0tMHSj81tFiILtt/FoIz8s+GxTUC18rV2y
  repository: win32service/win32service
  artifact: /php_win32service.*[7-8]{1}\.[0-4]{1}\.zip/
  force_update: true
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
